package gg.rsmod.plugins.content.inter.music

/**
 * @author Alan Simeon
 *
 * @param id : id of the Music Track
 * @param songName : name of Music Track
 * @param regionOptions : region played/unlocked in
 */

enum class MusicTracks(val id: Int, val slot: Int = -1, val varpId: Int = 1, val bitId: Int = -1, val songName: String, val regionOptions: Array<Int>) {
    SEVENTH_REALM(id = 363, slot = 262, varpId = 9, bitId = 29, songName = "7th Realm", regionOptions = arrayOf(10644,10645)),
    ADVENTURE(id = 177, slot = 21 , varpId = 1, bitId = 0, songName = "Adventure", regionOptions = arrayOf(12854)),
    AL_KHARID(id = 50, slot = 33 , varpId = 1, bitId = 1, songName = "Al Kharid", regionOptions = arrayOf(13105,13361)),
    ALCHEMICAL_ATTACK(id = 598, slot = 589, varpId = 19, bitId = 3, songName = "Alchemical Attack!", regionOptions = arrayOf(-1)), // Unlocked upon entering Alchemical Hydra Lair
    ALLS_FAIRY_IN_LOVE_AND_WAR(id = 73, slot = 423, varpId = 14, bitId = 20, songName = "All's Fairy in Love & War", regionOptions = arrayOf(9285)),
    ALONE(id = 102, slot = 50 , varpId = 1, bitId = 2, songName = "Alone", regionOptions = arrayOf(12086,10134,10390)),
    ALTAR_EGO(id = 486, slot = 526, varpId = 17, bitId = 4, songName = "Altar Ego", regionOptions = arrayOf(12119)),
    ALTERNATIVE_ROOT(id = 272, slot = 460, varpId = 15, bitId = 21, songName = "Alternative Root", regionOptions = arrayOf(12625)),
    AMBIENT_JUNGLE(id = 90, slot = 87 , varpId = 1, bitId = 3, songName = "Ambient Jungle", regionOptions = arrayOf(11310)),
    ANYWHERE(id = 305, slot = 244, varpId = 8, bitId = 16, songName = "Anywhere", regionOptions = arrayOf(10795)),
    ARABIAN(id = 36, slot = 32 , varpId = 1, bitId = 4, songName = "Arabian", regionOptions = arrayOf(13106,13617)),
    ARABIAN_2(id = 123, slot = 31 , varpId = 1, bitId = 5, songName = "Arabian 2", regionOptions = arrayOf(13107)),
    ARABIAN_3(id = 124, slot = 100, varpId = 1, bitId = 6, songName = "Arabian 3", regionOptions = arrayOf(12848)),
    ARABIQUE(id = 19, slot = 141, varpId = 1, bitId = 7, songName = "Arabique", regionOptions = arrayOf(11417)),
    ARACHNIDS_OF_VAMPYRIUM(id = 579, slot = 574, varpId = 18, bitId = 20, songName = "Arachnids of Vampyrium", regionOptions = arrayOf(-1)), // unlocked during fight in Nylocas lair within Theatre of Blood
    ARCANE(id = 455, slot = 509, varpId = 5, bitId = 24, songName = "Arcane", regionOptions = arrayOf(6458,6714,6715,6459)),
    ARCHITECTS_OF_PRIFDDINAS(id = 651, slot = 610, varpId = 19, bitId = 24, songName = "Architects of Prifddinas", regionOptions = arrayOf(12894,12895,13150,13151)),
    ARMADYL_ALLIANCE(id = 414, slot = 483, varpId = 16, bitId = 13, songName = "Armadyl Alliance", regionOptions = arrayOf(-1)), // GWD
    ARMAGEDDON(id = 404, slot = 482, varpId = 16, bitId = 14, songName = "Armageddon", regionOptions = arrayOf(-1)), // GWD
    ARMY_OF_DARKNESS(id = 160, slot = 108, varpId = 1, bitId = 8, songName = "Army of Darkness", regionOptions = arrayOf(12088)),
    ARRIVAL(id = 186, slot = 45 , varpId = 1, bitId = 9, songName = "Arrival", regionOptions = arrayOf(11572)),
    ARTISTRY(id = 247, slot = 204, varpId = 7, bitId = 8, songName = "Artistry", regionOptions = arrayOf(8010)), // Mime Random Event
    ASCENT(id = 494, slot = 532, varpId = 17, bitId = 11, songName = "Ascent", regionOptions = arrayOf(4662,4663,4664,4918,4919,4920,5174,5175,5176)),
    ASSAULT_AND_BATTERY(id = 604, slot = 448, varpId = 13, bitId = 23, songName = "Assault and Battery", regionOptions = arrayOf(7509,7508)), // Unlocked during Barbarian Assult Minigame
    ATTACK_1(id = 24, slot = 57 , varpId = 1, bitId = 10, songName = "Attack 1", regionOptions = arrayOf(-1)),
    ATTACK_2(id = 25, slot = 139, varpId = 1, bitId = 11, songName = "Attack 2", regionOptions = arrayOf(-1)),
    ATTACK_3(id = 26, slot = 147, varpId = 1, bitId = 12, songName = "Attack 3", regionOptions = arrayOf(-1)),
    ATTACK_4(id = 27, slot = 56 , varpId = 1, bitId = 13, songName = "Attack 4", regionOptions = arrayOf(-1)),
    ATTACK_5(id = 28, slot = 140, varpId = 1, bitId = 14, songName = "Attack 5", regionOptions = arrayOf(-1)),
    ATTACK_6(id = 29, slot = 137, varpId = 1, bitId = 15, songName = "Attack 6", regionOptions = arrayOf(-1)),
    ATTENTION(id = 180, slot = 112, varpId = 1, bitId = 16, songName = "Attention", regionOptions = arrayOf(11825)),
    AUTUMN_VOYAGE(id = 2, slot = 9 , varpId = 1, bitId = 17, songName = "Autumn Voyage", regionOptions = arrayOf(12851)),
    AYE_CAR_RUM_BA(id = 497, slot = 335, varpId = 11, bitId = 31, songName = "Aye Car Rum Ba", regionOptions = arrayOf(8527)),
    AZTEC(id = 248, slot = 205, varpId = 7, bitId = 9, songName = "Aztec", regionOptions = arrayOf(11157)),
    BACK_TO_LIFE(id = 616, slot = 409, varpId = 13, bitId = 30, songName = "Back to Life", regionOptions = arrayOf(-1)),
    BACKGROUND(id = 324, slot = 12 , varpId = 1, bitId = 18, songName = "Background", regionOptions = arrayOf(11060,11316,7758)),
    BAIT(id = 563, slot = 559, varpId = 18, bitId = 5, songName = "Bait", regionOptions = arrayOf(-1)),
    BALLAD_OF_ENCHANTMENT(id = 152, slot = 69 , varpId = 1, bitId = 19, songName = "Ballad of Enchantment", regionOptions = arrayOf(10290)),
    BANDIT_CAMP(id = 263, slot = 218, varpId = 7, bitId = 22, songName = "Bandit Camp", regionOptions = arrayOf(12590)),
    BANDOS_BATTALION(id = 408, slot = 484, varpId = 16, bitId = 12, songName = "Bandos Battalion", regionOptions = arrayOf(-1)),
    BANE(id = 430, slot = 498, varpId = 16, bitId = 25, songName = "Bane", regionOptions = arrayOf(-1)),
    BARB_WIRE(id = 367, slot = 468, varpId = 15, bitId = 25, songName = "Barb Wire", regionOptions = arrayOf(-1)),
    BARBARIANISM(id = 141, slot = 35 , varpId = 9, bitId = 1, songName = "Barbarianism", regionOptions = arrayOf(12341,12441)),
    BARKING_MAD(id = 345, slot = 270, varpId = 17, bitId = 5, songName = "Barking Mad", regionOptions = arrayOf(-1)),
    BAROQUE(id = 99, slot = 68 , varpId = 1, bitId = 20, songName = "Baroque", regionOptions = arrayOf(10547)),
    BARREN_LAND(id = 585, slot = 577, varpId = 18, bitId = 23, songName = "Barren Land", regionOptions = arrayOf(-1)),
    BEETLE_JUICE(id = 615, slot = 408, varpId = 13, bitId = 29, songName = "Beetle Juice", regionOptions = arrayOf(-1)),
    BENEATH_THE_STRONGHOLD(id = 417, slot = 488, varpId = 15, bitId = 31, songName = "Beneath the Stronghold", regionOptions = arrayOf(-1)),
    BEYOND(id = 100, slot = 162, varpId = 1, bitId = 21, songName = "Beyond", regionOptions = arrayOf(11418,11419,11675)),
    BIG_CHORDS(id = 83, slot = 113, varpId = 1, bitId = 22, songName = "Big Chords", regionOptions = arrayOf(10032)),
    BLISTERING_BARNACLES(id = 498, slot = 336, varpId = 12, bitId = 0, songName = "Blistering Barnacles", regionOptions = arrayOf(8528)),
    BLOODBATH(id = 557, slot = 561, varpId = 18, bitId = 7, songName = "Bloodbath", regionOptions = arrayOf(-1)),
    BODY_PARTS(id = 342, slot = 268, varpId = 9, bitId = 14, songName = "Body Parts", regionOptions = arrayOf(13979,14235)),
    BONE_DANCE(id = 154, slot = 189, varpId = 6, bitId = 23, songName = "Bone Dance", regionOptions = arrayOf(13619)),
    BONE_DRY(id = 266, slot = 220, varpId = 7, bitId = 24, songName = "Bone Dry", regionOptions = arrayOf(12946,13202)),
    BOOK_OF_SPELLS(id = 64, slot = 16 , varpId = 1, bitId = 23, songName = "Book of Spells", regionOptions = arrayOf(12593)),
    BORDERLAND(id = 291, slot = 238, varpId = 8, bitId = 9, songName = "Borderland", regionOptions = arrayOf(10809,10810)),
    BOX_OF_DELIGHTS(id = 637, slot = 600, varpId = 19, bitId = 14, songName = "Box of Delights", regionOptions = arrayOf(-1)),
    BREEZE(id = 132, slot = 198, varpId = 7, bitId = 2, songName = "Breeze", regionOptions = arrayOf(9010)),
    BREW_HOO_HOO(id = 471, slot = 321, varpId = 11, bitId = 18, songName = "Brew Hoo Hoo!", regionOptions = arrayOf(-1)),
    BRIMSTAILS_SCALES(id = 194, slot = 424, varpId = 14, bitId = 27, songName = "Brimstail's Scales", regionOptions = arrayOf(-1)),
    BUBBLE_AND_SQUEAK(id = 489, slot = 343, varpId = 11, bitId = 27, songName = "Bubble and Squeak", regionOptions = arrayOf(7753)),
    BUNNYS_SUGAR_RUSH(id = 437, slot = 502, varpId = 11, bitId = 0, songName = "Bunny's Sugar Rush", regionOptions = arrayOf(-1)),
    BURNING_DESIRE(id = 629, slot = 588, varpId = 19, bitId = 2, songName = "Burning Desire", regionOptions = arrayOf(-1)),
    CABIN_FEVER(id = 545, slot = 374, varpId = 12, bitId = 27, songName = "Cabin Fever", regionOptions = arrayOf(7243)),
    CAMELOT(id = 104, slot = 13 , varpId = 1, bitId = 24, songName = "Camelot", regionOptions = arrayOf(11062,11063)),
    CASTLE_WARS(id = 314, slot = 251, varpId = 8, bitId = 23, songName = "Castle Wars", regionOptions = arrayOf(9520)),
    CATCH_ME_IF_YOU_CAN(id = 481, slot = 345, varpId = 11, bitId = 24, songName = "Catch Me If You Can", regionOptions = arrayOf(10646)),
    CAVE_BACKGROUND(id = 325, slot = 146, varpId = 1, bitId = 25, songName = "Cave Background", regionOptions = arrayOf(11929,12185,12184,12183)),
    CAVE_OF_BEASTS(id = 357, slot = 277, varpId = 9, bitId = 24, songName = "Cave of Beasts", regionOptions = arrayOf(11165)),
    CAVE_OF_THE_GOBLINS(id = 389, slot = 278, varpId = 10, bitId = 16, songName = "Cave of the Goblins", regionOptions = arrayOf(12693,12949)),
    CAVERN(id = 68, slot = 172, varpId = 1, bitId = 26, songName = "Cavern", regionOptions = arrayOf(-1)),
    THE_CELLAR_DWELLERS(id = 478, slot = 325, varpId = 11, bitId = 22, songName = "The Cellar Dwellers", regionOptions = arrayOf(-1)),
    CELLAR_SONG(id = 330, slot = 19 , varpId = 6, bitId = 13, songName = "Cellar Song", regionOptions = arrayOf(12697)),
    CHAIN_OF_COMMAND(id = 63, slot = 158, varpId = 1, bitId = 27, songName = "Chain of Command", regionOptions = arrayOf(-1)),
    CHAMBER(id = 282, slot = 231, varpId = 8, bitId = 1, songName = "Chamber", regionOptions = arrayOf(-1)),
    CHEF_SURPRISE(id = 583, slot = 394, varpId = 13, bitId = 15, songName = "Chef Surprise", regionOptions = arrayOf(-1)),
    CHICKENED_OUT(id = 575, slot = 391, varpId = 13, bitId = 11, songName = "Chickened Out", regionOptions = arrayOf(-1)),
    CHOMPY_HUNT(id = 71, slot = 184, varpId = 6, bitId = 18, songName = "Chompy Hunt", regionOptions = arrayOf(-1)),
    THE_CHOSEN(id = 425, slot = 310, varpId = 11, bitId = 4, songName = "The Chosen", regionOptions = arrayOf(-1)),
    CITY_OF_THE_DEAD(id = 383, slot = 295, varpId = 10, bitId = 12, songName = "City of the Dead", regionOptions = arrayOf(12843,13099,12844)),
    CLAN_WARS(id = 428, slot = 494, varpId = 16, bitId = 22, songName = "Clan Wars", regionOptions = arrayOf(13641,13642,13130,13131,13386,13387)),
    CLAUSTROPHOBIA(id = 373, slot = 283, varpId = 10, bitId = 3, songName = "Claustrophobia", regionOptions = arrayOf(-1)),
    CLOSE_QUARTERS(id = 67, slot = 124, varpId = 6, bitId = 15, songName = "Close Quarters", regionOptions = arrayOf(12602)),
    COIL(id = 432, slot = 499, varpId = 14, bitId = 0, songName = "Coil", regionOptions = arrayOf(-1)),
    COMPETITION(id = 268, slot = 221, varpId = 7, bitId = 25, songName = "Competition", regionOptions = arrayOf(-1)),
    COMPLICATION(id = 142, slot = 168, varpId = 9, bitId = 2, songName = "Complication", regionOptions = arrayOf(-1)),
    CONSPIRACY(id = 561, slot = 558, varpId = 18, bitId = 4, songName = "Conspiracy", regionOptions = arrayOf(-1)),
    CONTEST(id = 258, slot = 212, varpId = 7, bitId = 16, songName = "Contest", regionOptions = arrayOf(-1)),
    CORPORAL_PUNISHMENT(id = 418, slot = 333, varpId = 11, bitId = 3, songName = "Corporal Punishment", regionOptions = arrayOf(12619)), // Drill Demon Random Event
    CORRIDORS_OF_POWER(id = 509, slot = 371, varpId = 12, bitId = 6, songName = "Corridors of Power", regionOptions = arrayOf(-1)),
    COUNTRY_JIG(id = 456, slot = 510, varpId = 5, bitId = 25, songName = "Country Jig", regionOptions = arrayOf(-1)),
    COURAGE(id = 178, slot = 148, varpId = 9, bitId = 4, songName = "Courage", regionOptions = arrayOf(-1)),
    CREATURE_CRUELTY(id = 234, slot = 444, varpId = 15, bitId = 20, songName = "Creature Cruelty", regionOptions = arrayOf(-1)),
    CREEPING_VINES(id = 596, slot = 599, varpId = 19, bitId = 13, songName = "Creeping Vines", regionOptions = arrayOf(-1)),
    CRYSTAL_CASTLE(id = 259, slot = 214, varpId = 7, bitId = 18, songName = "Crystal Castle", regionOptions = arrayOf(-1)),
    CRYSTAL_CAVE(id = 181, slot = 135, varpId = 1, bitId = 28, songName = "Crystal Cave", regionOptions = arrayOf(-1)),
    CRYSTAL_SWORD(id = 169, slot = 126, varpId = 1, bitId = 29, songName = "Crystal Sword", regionOptions = arrayOf(12855)),
    CURSED(id = 59, slot = 153, varpId = 6, bitId = 26, songName = "Cursed", regionOptions = arrayOf(-1)),
    THE_CURTAIN_CLOSES(id = 582, slot = 572, varpId = 18, bitId = 18, songName = "The Curtain Closes", regionOptions = arrayOf(-1)),
    DAGANNOTH_DAWN(id = 198, slot = 338, varpId = 12, bitId = 13, songName = "Dagannoth Dawn", regionOptions = arrayOf(-1)),
    DANCE_OF_DEATH(id = 560, slot = 383, varpId = 13, bitId = 6, songName = "Dance of Death", regionOptions = arrayOf(9297)), // Lowest floor of Stronghold of Security
    DANCE_OF_THE_MEILYR(id = 660, slot = 606, varpId = 19, bitId = 20, songName = "Band of the Meilyr", regionOptions = arrayOf(-1)),
    DANCE_OF_THE_NYLOCAS(id = 580, slot = 573, varpId = 18, bitId = 19, songName = "Dance of the Nylocas", regionOptions = arrayOf(-1)),
    DANCE_OF_THE_UNDEAD(id = 380, slot = 301, varpId = 10, bitId = 10, songName = "Dance of the Undead", regionOptions = arrayOf(14131)),
    DANGEROUS(id = 182, slot = 114, varpId = 1, bitId = 30, songName = "Dangrous", regionOptions = arrayOf(13115,13371,12343)),
    DANGEROUS_ROAD(id = 336, slot = 258, varpId = 9, bitId = 7, songName = "Dangerous Road", regionOptions = arrayOf(-1)),
    DANGEROUS_WAY(id = 381, slot = 302, varpId = 10, bitId = 11, songName = "Dangerous Way", regionOptions = arrayOf(-1)),
    DARK(id = 326, slot = 121, varpId = 1, bitId = 31, songName = "Dark", regionOptions = arrayOf(13113,13369)),
    THE_DARK_BEAST_SOTETSEG(id = 584, slot = 568, varpId = 18, bitId = 14, songName = "The Dark Beast Sotetseg", regionOptions = arrayOf(-1)),
    DARKLY_ALTARED(id = 472, slot = 522, varpId = 5, bitId = 30, songName = "Darkly Altared", regionOptions = arrayOf(-1)),
    DARKNESS_IN_THE_DEPTHS(id = 499, slot = 533, varpId = 17, bitId = 12, songName = "Darkness in the Depths", regionOptions = arrayOf(-1)),
    DAVY_JONES_LOCKER(id = 576, slot = 390, varpId = 13, bitId = 10, songName = "Davy Jones' Locker", regionOptions = arrayOf(-1)),
    DEAD_CAN_DANCE(id = 476, slot = 324, varpId = 11, bitId = 21, songName = "Dead Can Dance", regionOptions = arrayOf(12601)),
    DEAD_QUIET(id = 84, slot = 187, varpId = 6, bitId = 21, songName = "Dead Quiet", regionOptions = arrayOf(13621)),
    DEADLANDS(id = 288, slot = 235, varpId = 8, bitId = 6, songName = "Deadlands", regionOptions = arrayOf(14134,14390)),
    DEEP_DOWN(id = 278, slot = 230, varpId = 8, bitId = 0, songName = "Deep Down", regionOptions = arrayOf(-1)),
    DEEP_WILDY(id = 37, slot = 131, varpId = 2, bitId = 0, songName = "Deep Wildy", regionOptions = arrayOf(11835,11836)),
    THE_DEPTHS(id = 606, slot = 406, varpId = 13, bitId = 24, songName = "The Depths", regionOptions = arrayOf(-1)),
    DESERT_HEAT(id = 465, slot = 349, varpId = 11, bitId = 13, songName = "Desert Heat", regionOptions = arrayOf(13614,13615)),
    DESERT_VOYAGE(id = 174, slot = 99, varpId = 2, bitId = 1, songName = "Desert Voyage", regionOptions = arrayOf(13102,13103,13359)),
    THE_DESERT(id = 79, slot = 160, varpId = 4, bitId = 24, songName = "The Desert", regionOptions = arrayOf(12591,12847)),
    THE_DESOLATE_ISLE(id = 461, slot = 316, varpId = 11, bitId = 10, songName = "The Desolate Isle", regionOptions = arrayOf(-1)),
    THE_DESOLATE_MAGE(id = 495, slot = 529, varpId = 17, bitId = 8, songName = "The Desolate Mage", regionOptions = arrayOf(-1)),
    DEVILS_MAY_CARE(id = 424, slot = 492, varpId = 16, bitId = 20, songName = "Devils May Care", regionOptions = arrayOf(-1)),
    DIANGOS_LITTLE_HELPERS(id = 532, slot = 352, varpId = 12, bitId = 19, songName = "Diango's Little Helpers", regionOptions = arrayOf(-1)), // Diango's Workshop during 2013 Halloween Event, 2014 Christmas Event, and 2017 Christmas Event
    DIES_IRAE(id = 442, slot = 506, varpId = 12, bitId = 25, songName = "Dies Iraw", regionOptions = arrayOf(-1)), // Unlocked during 2015 Halloween Event
    DIMENSION_X(id = 86, slot = 422, varpId = 14, bitId = 19, songName = "Dimension X", regionOptions = arrayOf(-1)),
    DISTANT_LAND(id = 501, slot = 366, varpId = 12, bitId = 1, songName = "Distand Land", regionOptions = arrayOf(13873,13874,14130,14129)),
    DISTILLERY_HILARITY(id = 610, slot = 400, varpId = 13, bitId = 25, songName = "Distillery Hilarity", regionOptions = arrayOf(-1)),
    DOGS_OF_WAR(id = 537, slot = 380, varpId = 13, bitId = 3, songName = "Dogs of War", regionOptions = arrayOf(7505)),
    THE_DOORS_OF_DINH(id = 477, slot = 524, varpId = 4, bitId = 7, songName = "The Doors of Dinh", regionOptions = arrayOf(-1)),
    DOORWAYS(id = 56, slot = 17 , varpId = 2, bitId = 2, songName = "Doorways", regionOptions = arrayOf(12598)),
    DORGESHUUN_CITY(id = 240, slot = 446, varpId = 15, bitId = 5, songName = "Dorgeshuun City", regionOptions = arrayOf(-1)),
    DORGESHUUN_DEEP(id = 249, slot = 447, varpId = 15, bitId = 6, songName = "Dorgeshuun Deep", regionOptions = arrayOf(-1)),
    DOWN_AND_OUT(id = 301, slot = 471, varpId = 16, bitId = 7, songName = "Down and Out", regionOptions = arrayOf(-1)),
    DOWN_BELOW(id = 361, slot = 294, varpId = 9, bitId = 28, songName = "Down Below", regionOptions = arrayOf(12438,12439)),
    DOWN_BY_THE_DOCKS(id = 450, slot = 512, varpId = 5, bitId = 26, songName = "Down by the Docks", regionOptions = arrayOf(-1)),
    DOWN_TO_EARTH(id = 143, slot = 227, varpId = 9, bitId = 3, songName = "Down to Earth", regionOptions = arrayOf(10571)),
    THE_DRAGON_SLAYER(id = 543, slot = 547, varpId = 17, bitId = 26, songName = "The Dragon Slayer", regionOptions = arrayOf(-1)),
    DRAGONTOOTH_ISLAND(id = 358, slot = 274, varpId = 9, bitId = 25, songName = "Dragontooth Island", regionOptions = arrayOf(-1)),
    DREAM(id = 327, slot = 15 , varpId = 2, bitId = 3, songName = "Dream", regionOptions = arrayOf(12594)),
    DREAMSTATE(id = 623, slot = 411, varpId = 14, bitId = 3, songName = "Dreamstate", regionOptions = arrayOf(-1)),
    DUEL_ARENA(id = 47, slot = 179, varpId = 6, bitId = 4, songName = "Duel Arena", regionOptions = arrayOf(13362)),
    DUNJUN(id = 173, slot = 142, varpId = 2, bitId = 4, songName = "Dunjun", regionOptions = arrayOf(-1)),
    DWARF_THEME(id = 310, slot = 58 , varpId = 2, bitId = 20, songName = "Dwarf Theme", regionOptions = arrayOf(12085)),
    DWARVEN_DOMAIN(id = 446, slot = 511, varpId = 5, bitId = 23, songName = "Dwarven Domain", regionOptions = arrayOf(-1)),
    DYNASTY(id = 351, slot = 284, varpId = 9, bitId = 19, songName = "Dynasty", regionOptions = arrayOf(13358)),
    EAGLES_PEAK(id = 366, slot = 360, varpId = 10, bitId = 0, songName = "Eagles' Peak", regionOptions = arrayOf(-1)),
    EASTER_JIG(id = 273, slot = 462, varpId = 15, bitId = 27, songName = "Easter Jig", regionOptions = arrayOf(-1)), // Unlocked during 2014 Easter Event
    EGYPT(id = 69, slot = 98 , varpId = 2, bitId = 5, songName = "Egypt", regionOptions = arrayOf(13104,13360)),
    ELVEN_GUARDIANS(id = 647, slot = 617, varpId = 19, bitId = 30, songName = "Elven Guardians", regionOptions = arrayOf(-1)),
    ELVEN_MIST(id = 252, slot = 206, varpId = 7, bitId = 10, songName = "Elven Mist", regionOptions = arrayOf(-1)),
    ELVEN_SEED(id = 654, slot = 603, varpId = 19, bitId = 17, songName = "Elven Seed", regionOptions = arrayOf(-1)),
    EMOTION(id = 148, slot = 94 , varpId = 2, bitId = 6, songName = "Emotion", regionOptions = arrayOf(-1)),
    EMPEROR(id = 138, slot = 115, varpId = 2, bitId = 7, songName = "Emperor", regionOptions = arrayOf(11570)),
    THE_ENCHANTER(id = 541, slot = 353, varpId = 12, bitId = 24, songName = "The Enchanter", regionOptions = arrayOf(-1)),
    ESCAPE(id = 17, slot = 166, varpId = 6, bitId = 16, songName = "Escape", regionOptions = arrayOf(-1)),
    ESPIONAGE(id = 216, slot = 458, varpId = 15, bitId = 22, songName = "Espionage", regionOptions = arrayOf(-1)),
    ETCETERIA(id = 285, slot = 233, varpId = 8, bitId = 3, songName = "Etceteria", regionOptions = arrayOf(-1)),
    EVERLASTING(id = 283, slot = 475, varpId = 16, bitId = 5, songName = "Everlasting", regionOptions = arrayOf(-1)),
    EVERLASTING_FIRE(id = 586, slot = 399, varpId = 14, bitId = 1, songName = "Everlasting Fire", regionOptions = arrayOf(13373)),
    EVERYWHERE(id = 268, slot = 222, varpId = 7, bitId = 27, songName = "Everywhere", regionOptions = arrayOf(-1)),
    EVIL_BOBS_ISLAND(id = 411, slot = 317, varpId = 10, bitId = 28, songName = "Evil Bob's Island", regionOptions = arrayOf(10058)),
    EXPANSE(id = 106, slot = 26 , varpId = 2, bitId = 8, songName = "Expanse", regionOptions = arrayOf(12852,12605)),
    EXPECTING(id = 41, slot = 116, varpId = 2, bitId = 9, songName = "Expecting", regionOptions = arrayOf(-1)),
    EXPEDITION(id = 153, slot = 138, varpId = 2, bitId = 10, songName = "Expedition", regionOptions = arrayOf(-1)),
    EXPOSED(id = 270, slot = 223, varpId = 7, bitId = 28, songName = "Exposed", regionOptions = arrayOf(-1)),
    FAERIE(id = 118, slot = 134, varpId = 2, bitId = 11, songName = "Faerie", regionOptions = arrayOf(-1)),
    FAITH_OF_THE_HEFIN(id = 653, slot = 604, varpId = 19, bitId = 18, songName = "Faith of the Hefin", regionOptions = arrayOf(-1)),
    FAITHLESS(id = 337, slot = 119, varpId = 9, bitId = 9, songName = "Faithless", regionOptions = arrayOf(12856,13112)),
    FANFARE(id = 72, slot = 46 , varpId = 2, bitId = 12, songName = "Fanfare", regionOptions = arrayOf(11828)),
    FANFARE_2(id = 166, slot = 178, varpId = 6, bitId = 2, songName = "Fanfare 2", regionOptions = arrayOf(-1)),
    FANFARE_3(id = 167, slot = 95 , varpId = 2, bitId = 13, songName = "Fanfare 3", regionOptions = arrayOf(-1)),
    FANGS_FOR_THE_MEMORY(id = 504, slot = 367, varpId = 12, bitId = 2, songName = "Fangs for the Memory", regionOptions = arrayOf(-1)),
    FAR_AWAY(id = 372, slot = 311, varpId = 10, bitId = 4, songName = "Far Away", regionOptions = arrayOf(-1)),
    THE_FAR_SIDE(id = 403, slot = 309, varpId = 10, bitId = 26, songName = "The Far Side", regionOptions = arrayOf(-1)),
    A_FARMERS_GRIND(id = 609, slot = 592, varpId = 19, bitId = 6, songName = "A Farmer's Grind", regionOptions = arrayOf(-1)),
    THE_FAT_LADY_SINGS(id = 572, slot = 571, varpId = 18, bitId = 17, songName = "The Fat Lady Sings", regionOptions = arrayOf(-1)),
    FE_FI_FO_FUM(id = 23, slot = 478, varpId = 16, bitId = 1, songName = "Fe Fi Fo Fum", regionOptions = arrayOf(-1)),
    FEAR_AND_LOATHING(id = 602, slot = 388, varpId = 13, bitId = 21, songName = "Fear and Loathing", regionOptions = arrayOf(-1)),
    FENKENSTRAINS_REFRAIN(id = 344, slot = 269, varpId = 9, bitId = 15, songName = "Fenkenstrain's Refrain", regionOptions = arrayOf(14135,13879)),
    FIGHT_OR_FLIGHT(id = 375, slot = 312, varpId = 10, bitId = 5, songName = "Fight or Flight", regionOptions = arrayOf(-1)),
    FIND_MY_WAY(id = 312, slot = 250, varpId = 8, bitId = 22, songName = "Find My Way", regionOptions = arrayOf(-1)),
    FIRE_AND_BRIMSTONE(id = 463, slot = 328, varpId = 11, bitId = 14, songName = "Fire and Brimstone", regionOptions = arrayOf(-1)),
    FIRE_IN_THE_DEEP(id = 493, slot = 530, varpId = 17, bitId = 9, songName = "Fire in the Deep", regionOptions = arrayOf(-1)),
    THE_FIRES_OF_LLETYA(id = 658, slot = 618, varpId = 19, bitId = 31, songName = "The Fires of Lletya", regionOptions = arrayOf(-1)),
    FISHING(id = 119, slot = 41 , varpId = 2, bitId = 14, songName = "Fishing", regionOptions = arrayOf(-1)),
    FLOATING_FREE(id = 206, slot = 433, varpId = 15, bitId = 7, songName = "Floating Free", regionOptions = arrayOf(-1)),
    FLUTE_SALAD(id = 163, slot = 14 , varpId = 2, bitId = 15, songName = "Flute Salad", regionOptions = arrayOf(12595)),
    FOOD_FOR_THOUGHT(id = 558, slot = 381, varpId = 13, bitId = 4, songName = "Food for Thought", regionOptions = arrayOf(8017)),
    FORBIDDEN(id = 121, slot = 191, varpId = 6, bitId = 25, songName = "Forbidden", regionOptions = arrayOf(13367,13111)),
    FOREST(id = 251, slot = 207, varpId = 7, bitId = 11, songName = "Forest", regionOptions = arrayOf(-1)),
    FOREVER(id = 98, slot = 34, varpId = 2, bitId = 16, songName = "Forever", regionOptions = arrayOf(12342)),
    FORGETTABLE_MELODY(id = 436, slot = 313, varpId = 11, bitId = 6, songName = "Forgettable Melody", regionOptions = arrayOf(-1)),
    FORGOTTEN(id = 378, slot = 287, varpId = 10, bitId = 8, songName = "Forgotten", regionOptions = arrayOf(-1)),
    A_FORGOTTEN_RELIGION(id = 639, slot = 601, varpId = 19, bitId = 15, songName = "A Forgotten Religion", regionOptions = arrayOf(-1)),
    THE_FORLORN_HOMESTEAD(id = 452, slot = 514, varpId = 5, bitId = 27, songName = "The Forlorn Homestead", regionOptions = arrayOf(-1)),
    THE_FORSAKEN_TOWER(id = 624, slot = 596, varpId = 19, bitId = 10, songName = "The Forsaken Tower", regionOptions = arrayOf(-1)),
    THE_FORSAKEN(id = 527, slot = 551, varpId = 17, bitId = 30, songName = "The Forsaken", regionOptions = arrayOf(-1)),
    FOSSILISED(id = 514, slot = 538, varpId = 17, bitId = 17, songName = "Fossilised", regionOptions = arrayOf(-1)),
    THE_FRAGMENT(id = 652, slot = 621, varpId = 20, bitId = 2, songName = "The Fragment", regionOptions = arrayOf(-1)),
    FROGLAND(id = 409, slot = 319, varpId = 11, bitId = 16, songName = "Frogland", regionOptions = arrayOf(9802)), // Kiss the Frog Random Event
    FROSTBITE(id = 294, slot = 290, varpId = 8, bitId = 12, songName = "Frostbite", regionOptions = arrayOf(-1)),
    FRUITS_DE_MER(id = 347, slot = 54 , varpId = 9, bitId = 17, songName = "Fruits de Mer", regionOptions = arrayOf(11059)),
    FUL_TO_THE_BRIM(id = 635, slot = 585, varpId = 18, bitId = 31, songName = "Ful to the Brim", regionOptions = arrayOf(-1)),
    FUNNY_BUNNIES(id = 603, slot = 398, varpId = 13, bitId = 22, songName = "Funny Bunnies", regionOptions = arrayOf(-1)), // Unlocked during ANY Easter Event after 2013
    THE_GALLEON(id = 630, slot = 415, varpId = 14, bitId = 12, songName = "The Galleon", regionOptions = arrayOf(-1)),
    GAOL(id = 159, slot = 51 , varpId = 2, bitId = 17, songName = "Gaol", regionOptions = arrayOf(12090)),
    GARDEN(id = 125, slot = 25 , varpId = 2, bitId = 18, songName = "Garden", regionOptions = arrayOf(12853)),
    GARDEN_OF_AUTUMN(id = 228, slot = 455, varpId = 15, bitId = 17, songName = "Garden of Autumn", regionOptions = arrayOf(-1)),
    GARDEN_OF_SPRING(id = 229, slot = 453, varpId = 15, bitId = 15, songName = "Garden of Spring", regionOptions = arrayOf(-1)),
    GARDEN_OF_SUMMER(id = 230, slot = 454, varpId = 15, bitId = 14, songName = "Garden of Summer", regionOptions = arrayOf(-1)),
    GARDEN_OF_WINTER(id = 231, slot = 456, varpId = 15, bitId = 16, songName = "Garden of Winter", regionOptions = arrayOf(-1)),
    THE_GAUNTLET(id = 650, slot = 612, varpId = 19, bitId = 26, songName = "The Gauntlet", regionOptions = arrayOf(-1)),
    THE_GENIE(id = 464, slot = 348, varpId = 11, bitId = 12, songName = "The Genie", regionOptions = arrayOf(-1)),
    GETTING_DOWN_TO_BUSINESS(id = 617, slot = 593, varpId = 19, bitId = 7, songName = "Getting Down to Business", regionOptions = arrayOf(-1)),
    GILL_BILL(id = 618, slot = 582, varpId = 18, bitId = 28, songName = "Gill Bill", regionOptions = arrayOf(-1)),
    GNOME_KING(id = 22, slot = 74 , varpId = 2, bitId = 19, songName = "Gnome King", regionOptions = arrayOf(-1)),
    GNOME_VILLAGE(id = 33, slot = 75 , varpId = 2, bitId = 21, songName = "Gnome Village", regionOptions = arrayOf(-1)),
    GNOME_VILLAGE_2(id = 101, slot = 161, varpId = 2, bitId = 22, songName = "Gnome Village 2", regionOptions = arrayOf(-1)),
    GNOME_VILLAGE_PARTY(id = 416, slot = 487, bitId = -1, songName = "Gnome Village Party", regionOptions = arrayOf(-1)), // Unlocked Automatically
    GNOMEBALL(id = 112, slot = 117, varpId = 2, bitId = 24, songName = "Gnomeball", regionOptions = arrayOf(-1)),
    GOBLIN_GAME(id = 346, slot = 165, varpId = 8, bitId = 28, songName = "Goblin Game", regionOptions = arrayOf(-1)),
    GOBLIN_VILLAGE(id = 313, slot = 106, varpId = 2, bitId = 23, songName = "Goblin Village", regionOptions = arrayOf(11830)),
    GOLDEN_TOUCH(id = 535, slot = 355, varpId = 12, bitId = 22, songName = "Golden Touch", regionOptions = arrayOf(-1)),
    THE_GOLEM(id = 377, slot = 285, varpId = 10, bitId = 7, songName = "The Golem", regionOptions = arrayOf(13616,13872)),
    GREATNESS(id = 116, slot = 20 , varpId = 2, bitId = 25, songName = "Greatness", regionOptions = arrayOf(12596)),
    GRIMLY_FIENDISH(id = 431, slot = 496, varpId = 16, bitId = 29, songName = "Grimly Fiendish", regionOptions = arrayOf(-1)), // Unlocked during 2014 Halloween Event
    GRIP_OF_THE_TALON(id = 520, slot = 289, varpId = 12, bitId = 12, songName = "Grip of the Talon", regionOptions = arrayOf(-1)),
    GROTTO(id = 246, slot = 202, varpId = 7, bitId = 6, songName = "Grotto", regionOptions = arrayOf(-1)),
    GROW_GROW_GROW(id = 613, slot = 594, varpId = 19, bitId = 8, songName = "Grow Grow Grow", regionOptions = arrayOf(-1)),
    GRUMPY(id = 128, slot = 183, varpId = 6, bitId = 17, songName = "Grumpy", regionOptions = arrayOf(10286)),
    HAM_AND_SEEK(id = 276, slot = 465, varpId = 15, bitId = 30, songName = "H.A.M. and Seek", regionOptions = arrayOf(-1)),
    HAM_ATTACK(id = 279, slot = 463, varpId = 15, bitId = 28, songName = "H.A.M. Attack", regionOptions = arrayOf(-1)),
    HAM_FISTED(id = 638, slot = 419, varpId = 14, bitId = 13, songName = "H.A.M. Fisted", regionOptions = arrayOf(-1)),
    HARMONY(id = 76, slot = 6 , varpId = 2, bitId = 26, songName = "Harmony", regionOptions = arrayOf(12850)),
    HARMONY_2(id = 46, slot = 7 , varpId = 6, bitId = 7, songName = "Harmony 2", regionOptions = arrayOf(12950,12951)),
    HAUNTED_MINE(id = 277, slot = 228, varpId = 7, bitId = 30, songName = "Haunted Mine", regionOptions = arrayOf(-1)),
    HAVE_A_BLAST(id = 434, slot = 327, varpId = 11, bitId = 5, songName = "Have a Blast", regionOptions = arrayOf(-1)),
    HAVE_AN_ICE_DAY(id = 217, slot = 457, varpId = 15, bitId = 18, songName = "Have an Ice Day", regionOptions = arrayOf(-1)),
    HEAD_TO_HEAD(id = 612, slot = 402, varpId = 13, bitId = 27, songName = "Head to Head", regionOptions = arrayOf(7504)), // Evil Twin Random Event
    HEART_AND_MIND(id = 190, slot = 169, varpId = 6, bitId = 14, songName = "Heart and Mind", regionOptions = arrayOf(10059)),
    HELLS_BELLS(id = 4, slot = 256, varpId = 8, bitId = 30, songName = "Hells Bells", regionOptions = arrayOf(-1)),
    HERMIT(id = 97, slot = 195, varpId = 6, bitId = 31, songName = "Hermit", regionOptions = arrayOf(-1)),
    HIGH_SEAS(id = 55, slot = 42 , varpId = 2, bitId = 27, songName = "High Seas", regionOptions = arrayOf(-1)),
    HIGH_SPIRITS(id = 205, slot = 434, varpId = 15, bitId = 9, songName = "High Spirits", regionOptions = arrayOf(-1)), // Unlocked during Halloween Event in Draynor Village
    HOE_DOWN(id = 599, slot = 586, varpId = 19, bitId = 0, songName = "Hoe Down", regionOptions = arrayOf(-1)),
    HOME_SWEET_HOME(id = 454, slot = 378, varpId = 13, bitId = 1, songName = "Home Sweet Home", regionOptions = arrayOf(-1)),
    HORIZON(id = 18, slot = 96, varpId = 2, bitId = 28, songName = "Horizon", regionOptions = arrayOf(11573)),
    HYPNOTIZED(id = 384, slot = 297, varpId = 10, bitId = 13, songName = "Hypnotized", regionOptions = arrayOf(-1)),
    IBAN(id = 1, slot = 157, varpId = 2, bitId = 29, songName = "Iban", regionOptions = arrayOf(-1)),
    ICE_AND_FIRE(id = 483, slot = 525, varpId = 17, bitId = 3, songName = "Ice and Fire", regionOptions = arrayOf(-1)),
    ICE_MELODY(id = 157, slot = 182, varpId = 6, bitId = 5, songName = "Ice Melody", regionOptions = arrayOf(-1)),
    ILLUSIVE(id = 298, slot = 474, varpId = 16, bitId = 4, songName = "Illusive", regionOptions = arrayOf(-1)),
    IMPETUOUS(id = 349, slot = 469, varpId = 15, bitId = 26, songName = "Impetuous", regionOptions = arrayOf(-1)),
    IN_BETWEEN(id = 370, slot = 282, varpId = 10, bitId = 2, songName = "In Between", regionOptions = arrayOf(-1)),
    IN_THE_BRINE(id = 530, slot = 373, varpId = 12, bitId = 18, songName = "In the Brine", regionOptions = arrayOf(-1)),
    IN_THE_CLINK(id = 511, slot = 357, varpId = 12, bitId = 8, songName = "In the Clink", regionOptions = arrayOf(8261)), // Prison Pete Random Event
    IN_THE_MANOR(id = 188, slot = 123, varpId = 2, bitId = 30, songName = "In the Manor", regionOptions = arrayOf(-1)),
    IN_THE_PITS(id = 469, slot = 329, varpId = 11, bitId = 15, songName = "In the Pits", regionOptions = arrayOf(-1)),
    INADEQUACY(id = 299, slot = 473, varpId = 16, bitId = 3, songName = "Inadequacy", regionOptions = arrayOf(-1)),
    INCANTATION(id = 519, slot = 288, varpId = 12, bitId = 11, songName = "Incantation", regionOptions = arrayOf(-1)),
    INFERNO(id = 500, slot = 534, varpId = 17, bitId = 13, songName = "Inferno", regionOptions = arrayOf(-1)),
    INSECT_QUEEN(id = 260, slot = 216, varpId = 7, bitId = 20, songName = "Insect Queen", regionOptions = arrayOf(-1)),
    INSPIRATION(id = 96, slot = 107, varpId = 2, bitId = 31, songName = "Inspiration", regionOptions = arrayOf(12087)),
    INTO_THE_ABYSS(id = 412, slot = 307, varpId = 10, bitId = 29, songName = "Into the Abyss", regionOptions = arrayOf(-1)),
    INTREPID(id = 95, slot = 154, varpId = 3, bitId = 0, songName = "Intrepid", regionOptions = arrayOf(-1)),
    INVADER(id = 430, slot = 505, varpId = 12, bitId = 23, songName = "Invader", regionOptions = arrayOf(-1)),
    IORWERTHS_LAMENT(id = 644, slot = 607, varpId = 19, bitId = 21, songName = "Iorwerth's Lament", regionOptions = arrayOf(-1)),
    ISLAND_LIFE(id = 306, slot = 246, varpId = 8, bitId = 18, songName = "Island Life", regionOptions = arrayOf(-1)),
    ISLAND_OF_THE_TROLLS(id = 220, slot = 439, varpId = 14, bitId = 25, songName = "Island of the Trolls", regionOptions = arrayOf(-1)),
    ISLE_OF_EVERYWHERE(id = 627, slot = 413, varpId = 14, bitId = 5, songName = "Isle of Everywhere", regionOptions = arrayOf(-1)),
    ITS_NOT_OVER_TIL(id = 566, slot = 570, varpId = 18, bitId = 16, songName = "It's not over 'til...", regionOptions = arrayOf(-1)),
    JESTER_MINUTE(id = 221, slot = 436, varpId = 14, bitId = 22, songName = "Jester Minute", regionOptions = arrayOf(-1)),
    JOLLY_R(id = 6, slot = 76 , varpId = 3, bitId = 1, songName = "Jolly R", regionOptions = arrayOf(-1)),
    JOY_OF_THE_HUNT(id = 460, slot = 364, varpId = 13, bitId = 2, songName = "Joy of the Hunt", regionOptions = arrayOf(-1)),
    JUNGLE_BELLS(id = 209, slot = 452, varpId = 15, bitId = 13, songName = "Jungle Bells", regionOptions = arrayOf(-1)), // Unlocked during Christmas Event
    JUNGLE_HUNT(id = 453, slot = 363, varpId = 13, bitId = 0, songName = "Jungle Hunt", regionOptions = arrayOf(10129,10029,10285)),
    JUNGLE_ISLAND(id = 172, slot = 43 , varpId = 3, bitId = 2, songName = "Jungle Island", regionOptions = arrayOf(11313,11309)),
    JUNGLE_ISLAND_XMAS(id = 208, slot = 450, varpId = 15, bitId = 11, songName = "Juncle Island Xmas", regionOptions = arrayOf(-1)), // Unlocked During Christmas Event
    JUNGLE_TROUBLES(id = 479, slot = 326, varpId = 11, bitId = 23, songName = "Jungle Troubles", regionOptions = arrayOf(-1)),
    JUNGLY_1(id = 114, slot = 133, varpId = 3, bitId = 3, songName = "Jungly 1", regionOptions = arrayOf(-1)),
    JUNGLY_2(id = 115, slot = 125, varpId = 3, bitId = 4, songName = "Jungly 2", regionOptions = arrayOf(-1)),
    JUNGLY_3(id = 117, slot = 82 , varpId = 3, bitId = 5, songName = "Jungly 3", regionOptions = arrayOf(-1)),
    KANON_OF_KAHLITH(id = 608, slot = 584, varpId = 18, bitId = 30, songName = "Kanon of Kahlith", regionOptions = arrayOf(-1)),
    KARAMJA_JAM(id = 362, slot = 263, varpId = 9, bitId = 30, songName = "Karamja Jam", regionOptions = arrayOf(-1)),
    KINGDOM(id = 9, slot = 417, varpId = 6, bitId = 30, songName = "Kingdom", regionOptions = arrayOf(-1)),
    KNIGHTLY(id = 191, slot = 67 , varpId = 3, bitId = 6, songName = "Knightly", regionOptions = arrayOf(-1)),
    KNIGHTMARE(id = 374, slot = 480, varpId = 16, bitId = 18, songName = "Knightmare", regionOptions = arrayOf(7490)),
    KOUREND_THE_MAGNIFICENT(id = 451, slot = 508, varpId = 10, bitId = 17, songName = "Kourend the Magnificent", regionOptions = arrayOf(-1)),
    LA_MORT(id = 134, slot = 196, varpId = 7, bitId = 0, songName = "La Mort", regionOptions = arrayOf(-1)),
    LABYRINTH(id = 213, slot = 407, varpId = 13, bitId = 31, songName = "Labyrinth", regionOptions = arrayOf(-1)),
    LAGOON(id = 503, slot = 536, varpId = 17, bitId = 15, songName = "Lagoon", regionOptions = arrayOf(-1)),
    LAIR(id = 287, slot = 234, varpId = 8, bitId = 5, songName = "Lair", regionOptions = arrayOf(-1)),
    LAMENT(id = 542, slot = 377, varpId = 12, bitId = 29, songName = "Lament", regionOptions = arrayOf(-1)),
    LAMENT_OF_MEIYERDITCH(id = 197, slot = 425, varpId = 14, bitId = 14, songName = "Lament of Meiyerditch", regionOptions = arrayOf(-1)),
    LAND_DOWN_UNDER(id = 506, slot = 369, varpId = 12, bitId = 4, songName = "Land Down Under", regionOptions = arrayOf(-1)),
    LAND_OF_SNOW(id = 523, slot = 544, varpId = 17, bitId = 23, songName = "Land of Snow", regionOptions = arrayOf(-1)), // Unlocked During 2017 Christmas Event
    LAND_OF_THE_DWARVES(id = 396, slot = 279, varpId = 10, bitId = 22, songName = "Land of the Dwarves", regionOptions = arrayOf(-1)),
    LANDLUBBER(id = 164, slot = 83, varpId = 6, bitId = 9, songName = "Landlubber", regionOptions = arrayOf(-1)),
    LAST_KING_OF_THE_YARASA(id = 564, slot = 576, varpId = 18, bitId = 22, songName = "Last King of the Yarasa", regionOptions = arrayOf(-1)),
    LAST_MAN_STANDING(id = 474, slot = 523, varpId = 17, bitId = 2, songName = "Last Man Standing", regionOptions = arrayOf(-1)), // Unlocked in Last Man Standing Lobby
    THE_LAST_SHANTY(id = 643, slot = 426, varpId = 14, bitId = 16, songName = "The Last Shanty", regionOptions = arrayOf(-1)),
    LAST_STAND(id = 546, slot = 376, varpId = 12, bitId = 28, songName = "Last Stand", regionOptions = arrayOf(-1)),
    LASTING(id = 60, slot = 93 , varpId = 3, bitId = 7, songName = "Lasting", regionOptions = arrayOf(-1)),
    LAVA_IS_MINE(id = 507, slot = 537, varpId = 17, bitId = 16, songName = "Lava is Line", regionOptions = arrayOf(-1)),
    LEGEND(id = 293, slot = 239, varpId = 8, bitId = 11, songName = "Legend", regionOptions = arrayOf(-1)),
    LEGION(id = 66, slot = 97 , varpId = 3, bitId = 8, songName = "Legion", regionOptions = arrayOf(12089,10322,10039)), // 10322 is Barb Assult Lobby *UNDER BARB AGILITY*
    LIFES_A_BEACH(id = 631, slot = 404, varpId = 14, bitId = 8, songName = "Life's a Beach!", regionOptions = arrayOf(-1)),
    LIGHTHOUSE(id = 320, slot = 254, varpId = 8, bitId = 27, songName = "Lighthouse", regionOptions = arrayOf(-1)),
    LIGHTNESS(id = 113, slot = 323, varpId = 3, bitId = 9, songName = "Lightness", regionOptions = arrayOf(12599)),
    LIGHTWALK(id = 74, slot = 60 , varpId = 3, bitId = 10, songName = "Lightwalk", regionOptions = arrayOf(-1)),
    LITTLE_CAVE_OF_HORRORS(id = 632, slot = 405, varpId = 14, bitId = 10, songName = "Little Cave of Horrors", regionOptions = arrayOf(-1)),
    LONESOME(id = 168, slot = 80 , varpId = 5, bitId = 21, songName = "Lonesome", regionOptions = arrayOf(-1)),
    LONG_AGO(id = 161, slot = 104, varpId = 3, bitId = 11, songName = "Long Ago", regionOptions = arrayOf(-1)),
    LONG_WAY_HOME(id = 12, slot = 48 , varpId = 3, bitId = 12, songName = "Long Way Home", regionOptions = arrayOf(11826)),
    LOOKING_BACK(id = 309, slot = 467, varpId = 15, bitId = 10, songName = "Looking Back", regionOptions = arrayOf(6989,6477)), // Varrock Museum Basement
    LORE_AND_ORDER(id = 382, slot = 481, varpId = 16, bitId = 19, songName = "Lore and Order", regionOptions = arrayOf(-1)),
    THE_LOST_MELODY(id = 407, slot = 306, varpId = 10, bitId = 27, songName = "The Lost Melody", regionOptions = arrayOf(-1)),
    LOST_SOUL(id = 253, slot = 208, varpId = 7, bitId = 12, songName = "Lost Soul", regionOptions = arrayOf(-1)),
    THE_LOST_TRIBE(id = 420, slot = 8 , varpId = 11, bitId = 2, songName = "The Lost Tribe", regionOptions = arrayOf(-1)),
    LOWER_DEPTHS(id = 487, slot = 528, varpId = 17, bitId = 7, songName = "Lower Depths", regionOptions = arrayOf(-1)),
    LUCID_DREAM(id = 539, slot = 553, varpId = 18, bitId = 0, songName = "Lucid Dream", regionOptions = arrayOf(-1)),
    LUCID_NIGHTMARE(id = 531, slot = 554, varpId = 18, bitId = 1, songName = "Lucid Nightmare", regionOptions = arrayOf(-1)),
    LULLABY(id = 20, slot = 88 , varpId = 3, bitId = 13, songName = "Lullaby", regionOptions = arrayOf(13365)),
    LUMBERING(id = 590, slot = 578, varpId = 18, bitId = 24, songName = "Lumbering", regionOptions = arrayOf(-1)),
    THE_LUNAR_ISLE(id = 625, slot = 412, varpId = 14, bitId = 4, songName = "The Lunar Isle", regionOptions = arrayOf(-1)),
    MAD_EADGAR(id = 264, slot = 217, varpId = 7, bitId = 21, songName = "Mad Eadgar", regionOptions = arrayOf(-1)),
    THE_MAD_MOLE(id = 573, slot = 389, varpId = 13, bitId = 9, songName = "The Mad Mole", regionOptions = arrayOf(-1)),
    MAGE_ARENA(id = 13, slot = 167, varpId = 3, bitId = 14, songName = "Mage Arena", regionOptions = arrayOf(12349)),
    MAGIC_DANCE(id = 185, slot = 105, varpId = 3, bitId = 15, songName = "Magic Dance", regionOptions = arrayOf(-1)),
    MAGIC_MAGIC_MAGIC(id = 235, slot = 443, varpId = 15, bitId = 3, songName = "Magic, Magic, Magic", regionOptions = arrayOf(-1)),
    MAGICAL_JOURNEY(id = 184, slot = 53 , varpId = 3, bitId = 16, songName = "Magical Journey", regionOptions = arrayOf(-1)),
    THE_MAIDENS_ANGER(id = 569, slot = 565, varpId = 18, bitId = 11, songName = "The Maiden's Anger", regionOptions = arrayOf(-1)),
    THE_MAIDENS_SORROW(id = 570, slot = 564, varpId = 18, bitId = 10, songName = "The Maiden's Sorrow", regionOptions = arrayOf(-1)),
    MAJOR_MINER(id = 222, slot = 435, varpId = 14, bitId = 21, songName = "Major Minor", regionOptions = arrayOf(-1)),
    MAKING_WAVES(id = 544, slot = 375, varpId = 12, bitId = 26, songName = "Making Waves", regionOptions = arrayOf(-1)),
    MALADY(id = 559, slot = 382, varpId = 13, bitId = 5, songName = "Malady", regionOptions = arrayOf(8530)),
    MARCH(id = 328, slot = 65 , varpId = 3, bitId = 17, songName = "March", regionOptions = arrayOf(-1)),
    MARCH_OF_THE_SHAYZIEN(id = 488, slot = 527, varpId = 17, bitId = 6, songName = "March of the Shayzien", regionOptions = arrayOf(-1)),
    MAROONED(id = 304, slot = 245, varpId = 8, bitId = 17, songName = "Marooned", regionOptions = arrayOf(-1)),
    MARZIPAN(id = 261, slot = 215, varpId = 7, bitId = 19, songName = "Marzipan", regionOptions = arrayOf(-1)),
    MASQUERADE(id = 340, slot = 266, varpId = 9, bitId = 12, songName = "Masquerade", regionOptions = arrayOf(-1)),
    MASTERMINDLESS(id = 577, slot = 392, varpId = 13, bitId = 13, songName = "Mastermindless", regionOptions = arrayOf(-1)),
    MAUSOLEUM(id = 156, slot = 190, varpId = 6, bitId = 24, songName = "Mausoleum", regionOptions = arrayOf(-1)),
    MAWS_JAWS_AND_CLAWS(id = 439, slot = 503, varpId = 16, bitId = 26, songName = "Maws, Jaws & Claws", regionOptions = arrayOf(-1)),
    THE_MAZE(id = 365, slot = 479, varpId = 16, bitId = 9, songName = "The Maze", regionOptions = arrayOf(-1)), // Melzars Maze
    MEDDLING_KIDS(id = 508, slot = 370, varpId = 12, bitId = 5, songName = "Meddling Kids", regionOptions = arrayOf(-1)),
    MEDIEVAL(id = 157, slot = 29 , varpId = 3, bitId = 18, songName = "Medieval", regionOptions = arrayOf(13109)),
    MELLOW(id = 193, slot = 59 , varpId = 3, bitId = 19, songName = "Mellow", regionOptions = arrayOf(-1)),
    MELODRAMA(id = 317, slot = 252, varpId = 8, bitId = 24, songName = "Melodrama", regionOptions = arrayOf(9776)),
    MERIDIAN(id = 254, slot = 209, varpId = 7, bitId = 13, songName = "Meridian", regionOptions = arrayOf(-1)),
    METHOD_OF_MADNESS(id = 600, slot = 387, varpId = 13, bitId = 20, songName = "Method of Madness", regionOptions = arrayOf(-1)),
    MILES_AWAY(id = 107, slot = 47 , varpId = 3, bitId = 20, songName = "Miles Away", regionOptions = arrayOf(11571)),
    THE_MILITIA(id = 449, slot = 513, varpId = 5, bitId = 22, songName = "The Militia", regionOptions = arrayOf(-1)),
    MIND_OVER_MATTER(id = 534, slot = 356, varpId = 12, bitId = 21, songName = "Mind over Matter", regionOptions = arrayOf(-1)),
    MIRACLE_DANCE(id = 65, slot = 173, varpId = 3, bitId = 21, songName = "Miracle Dance", regionOptions = arrayOf(11083)),
    MIRAGE(id = 388, slot = 298, varpId = 10, bitId = 15, songName = "Mirage", regionOptions = arrayOf(-1)),
    MISCELLANIA(id = 284, slot = 232, varpId = 8, bitId = 2, songName = "Miscellania", regionOptions = arrayOf(-1)),
    THE_MOLLUSC_MENACE(id = 200, slot = 430, varpId = 14, bitId = 11, songName = "The Mollusc Menace", regionOptions = arrayOf(-1)),
    MONARCH_WALTZ(id = 21, slot = 70 , varpId = 3, bitId = 22, songName = "Monarch Waltz", regionOptions = arrayOf(-1)),
    MONKEY_BADNESS(id = 468, slot = 520, varpId = 17, bitId = 1, songName = "Monkey Badness", regionOptions = arrayOf(-1)),
    MONKEY_BUSINESS(id = 467, slot = 519, varpId = 17, bitId = 0, songName = "Monkey Business", regionOptions = arrayOf(-1)),
    MONKEY_MADNESS(id = 303, slot = 243, varpId = 8, bitId = 15, songName = "Monkey Madness", regionOptions = arrayOf(-1)),
    MONKEY_SADNESS(id = 459, slot = 518, varpId = 16, bitId = 31, songName = "Monkey Sadness", regionOptions = arrayOf(-1)),
    MONKEY_TROUBLE(id = 457, slot = 517, varpId = 16, bitId = 30, songName = "Monkey Trouble", regionOptions = arrayOf(-1)),
    MONSTER_MELEE(id = 343, slot = 275, varpId = 9, bitId = 16, songName = "Monster Melee", regionOptions = arrayOf(-1)),
    THE_MONSTERS_BELOW(id = 448, slot = 315, varpId = 11, bitId = 9, songName = "The Monsters Below", regionOptions = arrayOf(-1)),
    MOODY(id = 10, slot = 102, varpId = 3, bitId = 23, songName = "Moody", regionOptions = arrayOf(12600)),
    MOR_UL_REK(id = 502, slot = 535, varpId = 17, bitId = 14, songName = "Mor Ul Rek", regionOptions = arrayOf(-1)),
    MORYTANIA(id = 48, slot = 186, varpId = 6, bitId = 20, songName = "Morytania", regionOptions = arrayOf(13622)),
    MOTHER_RUCKUS(id = 593, slot = 581, varpId = 18, bitId = 27, songName = "Mother Ruckus", regionOptions = arrayOf(-1)),
    MOUSE_TRAP(id = 150, slot = 477, varpId = 16, bitId = 0, songName = "Mouse Trap", regionOptions = arrayOf(-1)),
    MUDSKIPPER_MELODY(id = 515, slot = 334, varpId = 12, bitId = 9, songName = "Mudskipper Melody", regionOptions = arrayOf(11824)),
    MUSEUM_MEDLEY(id = 553, slot = 555, varpId = 18, bitId = 2, songName = "Museum Medley", regionOptions = arrayOf(-1)), // Unlocked in basement of Falador Party Room
    MUTANT_MEDLEY(id = 236, slot = 445, varpId = 15, bitId = 4, songName = "Mutant Medley", regionOptions = arrayOf(-1)),
    MY_ARMS_JOURNEY(id = 203, slot = 428, varpId = 14, bitId = 28, songName = "My Arm's Journey", regionOptions = arrayOf(-1)),
    MYSTICS_OF_NATURE(id = 655, slot = 608, varpId = 19, bitId = 22, songName = "Mystics of Nature", regionOptions = arrayOf(-1)),
    MYTHICAL(id = 550, slot = 548, varpId = 17, bitId = 27, songName = "Mythical", regionOptions = arrayOf(-1)),
    NARNODES_THEME(id = 303, slot = 164, varpId = 9, bitId = 18, songName = "Narnode's Theme", regionOptions = arrayOf(-1)),
    NATURAL(id = 245, slot = 201, varpId = 7, bitId = 5, songName = "Natural", regionOptions = arrayOf(13620)),
    THE_NAVIGATOR(id = 316, slot = 241, varpId = 8, bitId = 31, songName = "The Navigator", regionOptions = arrayOf(-1)),
    NETHER_REALM(id = 422, slot = 490, varpId = 16, bitId = 16, songName = "Nether Realm", regionOptions = arrayOf(-1)),
    NEVERLAND(id = 155, slot = 101, varpId = 3, bitId = 24, songName = "Neverland", regionOptions = arrayOf(-1)),
    NEWBIE_FARMING(id = 597, slot = 591, varpId = 19, bitId = 5, songName = "Newbie Farming", regionOptions = arrayOf(-1)),
    NEWBIE_MELODY(id = 62, slot = 127, bitId = -1, songName = "Newbie Melody", regionOptions = arrayOf(12079,12080,12336,12592,12335)),
    NIGHT_OF_THE_VAMPYRE(id = 646, slot = 427, varpId = 14, bitId = 17, songName = "Night of the Vampyre", regionOptions = arrayOf(-1)),
    NIGHTFALL(id = 127, slot = 52 , varpId = 3, bitId = 26, songName = "Nightfall", regionOptions = arrayOf(11827,12861)),
    THE_NIGHTMARE_CONTINUES(id = 571, slot = 567, varpId = 18, bitId = 13, songName = "The Nightmare Continues", regionOptions = arrayOf(-1)),
    NO_PASARAN(id = 642, slot = 620, varpId = 20, bitId = 1, songName = "No Pasaran", regionOptions = arrayOf(-1)),
    NO_WAY_OUT(id = 594, slot = 386, varpId = 13, bitId = 19, songName = "No Way Out", regionOptions = arrayOf(-1)),
    THE_NOBLE_RODENT(id = 485, slot = 342, varpId = 11, bitId = 26, songName = "The Noble Rodent", regionOptions = arrayOf(-1)),
    NOMAD(id = 58, slot = 77 , varpId = 6, bitId = 11, songName = "Nomad", regionOptions = arrayOf(-1)),
    NORSE_CODE(id = 223, slot = 437, varpId = 14, bitId = 23, songName = "Norse Code", regionOptions = arrayOf(-1)),
    NOX_IRAE(id = 443, slot = 507, varpId = 12, bitId = 31, songName = "Nox Irae", regionOptions = arrayOf(-1)), // Unlocked during 2015 Halloween Event
    NULL_AND_VOID(id = 587, slot = 395, varpId = 13, bitId = 16, songName = "Null and Void", regionOptions = arrayOf(-1)),
    OGRE_THE_TOP(id = 224, slot = 440, varpId = 15, bitId = 1, songName = "Ogre the Top", regionOptions = arrayOf(-1)),
    ON_THE_FRONTLINE(id = 605, slot = 597, varpId = 19, bitId = 11, songName = "On the Frontline", regionOptions = arrayOf(-1)),
    ON_THE_SHORE(id = 522, slot = 543, varpId = 17, bitId = 22, songName = "On the Shore", regionOptions = arrayOf(10284,10028)),
    ON_THE_UP(id = 302, slot = 472, varpId = 16, bitId = 8, songName = "On the Up", regionOptions = arrayOf(-1)),
    ON_THE_WING(id = 633, slot = 365, varpId = 14, bitId = 9, songName = "On the Wing", regionOptions = arrayOf(-1)),
    ON_THIN_ICE(id = 536, slot = 549, varpId = 17, bitId = 28, songName = "On Thin Ice", regionOptions = arrayOf(-1)),
    ONCOMING_FOE(id = 540, slot = 552, varpId = 17, bitId = 31, songName = "Oncoming Foe", regionOptions = arrayOf(-1)),
    ORIENTAL(id = 103, slot = 145, varpId = 3, bitId = 27, songName = "Oriental", regionOptions = arrayOf(-1)),
    THE_OTHER_SIDE(id = 355, slot = 273, varpId = 9, bitId = 22, songName = "The Other Side", regionOptions = arrayOf(14646,14647)),
    OUT_OF_THE_DEEP(id = 322, slot = 255, varpId = 8, bitId = 29, songName = "Out of the Deep", regionOptions = arrayOf(-1)),
    OVER_TO_NARDAH(id = 447, slot = 346, varpId = 11, bitId = 8, songName = "Over to Nardah", regionOptions = arrayOf(13613)),
    OVERPASS(id = 256, slot = 211, varpId = 7, bitId = 15, songName = "Overpass", regionOptions = arrayOf(-1)),
    OVERTURE(id = 7, slot = 71 , varpId = 3, bitId = 28, songName = "Overture", regionOptions = arrayOf(-1)),
    PARADE(id = 93, slot = 28 , varpId = 3, bitId = 29, songName = "Parade", regionOptions = arrayOf(13110,13366)),
    PATH_OF_PERIL(id = 393, slot = 293, varpId = 10, bitId = 19, songName = "Path of Peril", regionOptions = arrayOf(-1)),
    PATHWAYS(id = 364, slot = 264, varpId = 9, bitId = 31, songName = "Pathways", regionOptions = arrayOf(-1)),
    PEST_CONTROL(id = 588, slot = 396, varpId = 13, bitId = 17, songName = "Pest Control", regionOptions = arrayOf(-1)),
    PHAROHS_TOMB(id = 505, slot = 368, varpId = 12, bitId = 3, songName = "Pharoh's Tomb", regionOptions = arrayOf(13356)),
    PHASMATYS(id = 354, slot = 272, varpId = 9, bitId = 21, songName = "Phasmatys", regionOptions = arrayOf(-1)),
    PHEASANT_PEASANT(id = 419, slot = 318, varpId = 11, bitId = 1, songName = "Pheasant Peasant", regionOptions = arrayOf(10314)), // Freaky Forester Random Event
    PICK_AND_SHOVEL(id = 426, slot = 493, varpId = 16, bitId = 21, songName = "Pick and Shovel", regionOptions = arrayOf(14936)),
    PINBALL_WIZARD(id = 614, slot = 403, varpId = 13, bitId = 28, songName = "Pinball Wizard", regionOptions = arrayOf(-1)), // Pinball Random Event
    PIRATES_OF_PENANCE(id = 211, slot = 449, varpId = 14, bitId = 26, songName = "Pirates of Penance", regionOptions = arrayOf(-1)),
    PIRATES_OF_PERIL(id = 334, slot = 257, varpId = 9, bitId = 6, songName = "Pirates of Peril", regionOptions = arrayOf(12093)),
    POLES_APART(id = 548, slot = 362, varpId = 12, bitId = 30, songName = "Poles Apart", regionOptions = arrayOf(-1)),
    THE_POWER_OF_TEARS(id = 398, slot = 300, varpId = 10, bitId = 31, songName = "The Power of Tears", regionOptions = arrayOf(-1)),
    POWER_OF_THE_SHADOW_REALM(id = 581, slot = 569, varpId = 18, bitId = 15, songName = "Power of the Shadow Realm", regionOptions = arrayOf(-1)),
    PREDATOR_XARPUS(id = 567, slot = 575, varpId = 18, bitId = 21, songName = "Predator Xarpus", regionOptions = arrayOf(-1)),
    PRESERVATION(id = 512, slot = 540, varpId = 17, bitId = 19, songName = "Preservation", regionOptions = arrayOf(-1)),
    PRESERVED(id = 513, slot = 539, varpId = 17, bitId = 18, songName = "Preserved", regionOptions = arrayOf(-1)),
    PRIME_TIME(id = 202, slot = 432, varpId = 14, bitId = 30, songName = "Prime Time", regionOptions = arrayOf(-1)),
    PRINCIPALITY(id = 149, slot = 193, varpId = 6, bitId = 28, songName = "Principality", regionOptions = arrayOf(11575)),
    QUEST(id = 158, slot = 174, varpId = 3, bitId = 30, songName = "Quest", regionOptions = arrayOf(10315)),
    THE_QUIZMASTER(id = 413, slot = 320, varpId = 10, bitId = 30, songName = "The Quizmaster", regionOptions = arrayOf(7754)), // Quizmaster Random Event
    RAT_A_TAT_TAT(id = 482, slot = 341, varpId = 11, bitId = 25, songName = "Rat a Tat Tat", regionOptions = arrayOf(-1)),
    RAT_HUNT(id = 491, slot = 340, varpId = 11, bitId = 29, songName = "Rat Hunt", regionOptions = arrayOf(-1)),
    READY_FOR_BATTLE(id = 318, slot = 253, varpId = 8, bitId = 25, songName = "Ready for Battle", regionOptions = arrayOf(9620)), // Castle Wars Waiting Room(s) and Underground
    REGAL(id = 329, slot = 159, varpId = 3, bitId = 31, songName = "Regal", regionOptions = arrayOf(13117)),
    REGGAE(id = 78, slot = 79 , varpId = 4, bitId = 0, songName = "Reggae", regionOptions = arrayOf(-1)),
    REGGAE_2(id = 89, slot = 85 , varpId = 4, bitId = 1, songName = "Reggae 2", regionOptions = arrayOf(-1)),
    RELICS(id = 549, slot = 546, varpId = 17, bitId = 25, songName = "Relics", regionOptions = arrayOf(-1)),
    RELLEKKA(id = 289, slot = 236, varpId = 8, bitId = 7, songName = "Rellekka", regionOptions = arrayOf(-1)),
    REVENANTS(id = 521, slot = 542, varpId = 17, bitId = 21, songName = "Revenants", regionOptions = arrayOf(-1)),
    RIGHT_ON_TRACK(id = 44, slot = 314, varpId = 11, bitId = 7, songName = "Right on Track", regionOptions = arrayOf(-1)),
    RIGHTEOUSNESS(id = 262, slot = 225, songName = "Righteousness", regionOptions = arrayOf(-1)),
    RISING_DAMP(id = 274, slot = 441, varpId = 14, bitId = 31, songName = "Rising Damp", regionOptions = arrayOf(-1)),
    RIVERSIDE(id = 91, slot = 225, varpId = 7, bitId = 29, songName = "Riverside", regionOptions = arrayOf(-1)),
    ROC_AND_ROLL(id = 204, slot = 429, varpId = 15, bitId = 8, songName = "Roc and Roll", regionOptions = arrayOf(-1)),
    THE_ROGUES_DEN(id = 402, slot = 308, varpId = 10, bitId = 25, songName = "The Rogues Den", regionOptions = arrayOf(-1)),
    ROLL_OF_BONES(id = 533, slot = 354, varpId = 12, bitId = 20, songName = "Roll of Bones", regionOptions = arrayOf(-1)),
    ROMANCING_THE_CRONE(id = 335, slot = 259, varpId = 9, bitId = 8, songName = "Romancing the Crone", regionOptions = arrayOf(-1)),
    ROMPER_CHOMPER(id = 390, slot = 305, varpId = 10, bitId = 24, songName = "Romper Chomper", regionOptions = arrayOf(-1)),
    ROOTS_AND_FLUTES(id = 554, slot = 557, varpId = 18, bitId = 3, songName = "Roots and Flutes", regionOptions = arrayOf(12955)),
    ROYALE(id = 53, slot = 136, varpId = 4, bitId = 3, songName = "Royale", regionOptions = arrayOf(-1)),
    RUGGED_TERRAIN(id = 445, slot = 516, varpId = 5, bitId = 29, songName = "Rugged Terrain", regionOptions = arrayOf(-1)),
    RUNE_ESSENCE(id = 57, slot = 149, varpId = 4, bitId = 4, songName = "Rune Essence", regionOptions = arrayOf(11595)),
    SAD_MEADOW(id = 5, slot = 66 , varpId = 4, bitId = 5, songName = "Sad Meadow", regionOptions = arrayOf(-1)),
    SAGA(id = 290, slot = 237, varpId = 8, bitId = 8, songName = "Saga", regionOptions = arrayOf(-1)),
    SARACHNIS(id = 641, slot = 602, varpId = 19, bitId = 16, songName = "Sarachnis", regionOptions = arrayOf(-1)),
    SARCOPHAGUS(id = 359, slot = 292, varpId = 9, bitId = 27, songName = "Sarcophagus", regionOptions = arrayOf(-1)),
    SARIMS_VERMIN(id = 490, slot = 344, varpId = 11, bitId = 28, songName = "Sarims Vermin", regionOptions = arrayOf(-1)),
    SCAPE_APE(id = 458, slot = 521, bitId = -1, songName = "Scape Ape", regionOptions = arrayOf(-1)), // Unlocked Automatically
    SCAPE_CAVE(id = 144, slot = 27 , varpId = 4, bitId = 6, songName = "Scape Cave", regionOptions = arrayOf(12698,12954,13210,12436)), /// 12436 is Tutorial Island Underground
    SCAPE_CRYSTAL(id = 661, slot = 615, bitId = -1, songName = "Scape Crystal", regionOptions = arrayOf(-1)), // Unlocked Automatically
    SCAPE_FIVE(id = 552, slot = 556, bitId = -1, songName = "Scape Five", regionOptions = arrayOf(-1)), // Unlocked Automatically
    SCAPE_GROUND(id = 466, slot = 2, bitId = -1, songName = "Scape Ground", regionOptions = arrayOf(-1)), // Unlocked Automatically
    SCAPE_HOME(id = 621, slot = 379, bitId = -1, songName = "Scape Home", regionOptions = arrayOf(-1)), // Unlocked Automatically
    SCAPE_HUNTER(id = 207, slot = 359, bitId = -1, songName = "Scape Hunter", regionOptions = arrayOf(-1)), // Unlocked Automatically
    SCAPE_MAIN(id = 0, slot = 1, bitId = -1, songName = "Scape Main", regionOptions = arrayOf(-1)), // Unlocked Automatically
    SCAPE_ORIGINAL(id = 400, slot = 0, bitId = -1, songName = "Scape Original", regionOptions = arrayOf(-1)), // Unlocked Automatically
    SCAPE_SAD(id = 331, slot = 24 , varpId = 4, bitId = 8, songName = "Scape Sad", regionOptions = arrayOf(13116,13372)),
    SCAPE_SANTA(id = 547, slot = 4, bitId = -1, songName = "Scape Santa", regionOptions = arrayOf(-1)), // Unlocked Automatically
    SCAPE_SCARED(id = 321, slot = 3, bitId = -1, songName = "Scape Scared", regionOptions = arrayOf(-1)), // Unlocked Automatically
    SCAPE_SOFT(id = 54, slot = 175, varpId = 5, bitId = 31, songName = "Scape Soft", regionOptions = arrayOf(11829)),
    SCAPE_WILD(id = 332, slot = 22 , varpId = 4, bitId = 9, songName = "Scape Wild", regionOptions = arrayOf(12604,12860,12857)),
    SCARAB(id = 352, slot = 291, varpId = 9, bitId = 26, songName = "Scarab", regionOptions = arrayOf(12589,12845,13101)),
    SCHOOLS_OUT(id = 371, slot = 470, varpId = 16, bitId = 2, songName = "School's Out", regionOptions = arrayOf(7502)), // Surprise Exam Random Event
    SCORPIA_DANCES(id = 423, slot = 491, varpId = 16, bitId = 17, songName = "Scorpia Dances", regionOptions = arrayOf(-1)),
    SEA_SHANTY(id = 96, slot = 44 , varpId = 4, bitId = 10, songName = "Sea Shanty", regionOptions = arrayOf(11569)),
    SEA_SHANTY_2(id = 35, slot = 40 , varpId = 4, bitId = 11, songName = "Sea Shanty 2", regionOptions = arrayOf(12082)),
    SEA_SHANTY_XMAS(id = 210, slot = 451, varpId = 15, bitId = 12, songName = "Sea Shanty Xmas", regionOptions = arrayOf(-1)), // Unlocked at a Christmas Event
    THE_SEED_OF_CRWYS(id = 659, slot = 609, varpId = 19, bitId = 23, songName = "The Seed of Crwys", regionOptions = arrayOf(-1)),
    SERENADE(id = 110, slot = 103, varpId = 4, bitId = 12, songName = "Serenade", regionOptions = arrayOf(-1)),
    SERENE(id = 52, slot = 171, varpId = 4, bitId = 13, songName = "Serene", regionOptions = arrayOf(11837,11339)),
    SERVANTS_OF_STRIFE(id = 628, slot = 598, varpId = 19, bitId = 12, songName = "Servants of Strife", regionOptions = arrayOf(-1)),
    SETTLEMENT(id = 356, slot = 276, varpId = 9, bitId = 23, songName = "Settlement", regionOptions = arrayOf(-1)),
    THE_SHADOW(id = 170, slot = 61 , varpId = 4, bitId = 25, songName = "The Shadow", regionOptions = arrayOf(11315,11314)),
    SHADOWLAND(id = 286, slot = 180, varpId = 8, bitId = 4, songName = "Shadowland", regionOptions = arrayOf(13618,13875)),
    SHARP_END_OF_THE_CRYSTAL(id = 657, slot = 614, varpId = 19, bitId = 28, songName = "Sharp End of the Crystal", regionOptions = arrayOf(-1)),
    SHINE(id = 122, slot = 181, varpId = 4, bitId = 14, songName = "Shine", regionOptions = arrayOf(13363)),
    SHINING(id = 120, slot = 176, varpId = 6, bitId = 0, songName = "Shining", regionOptions = arrayOf(12858)),
    SHINING_SPIRIT(id = 429, slot = 497, varpId = 16, bitId = 24, songName = "Shining Spirit", regionOptions = arrayOf(-1)),
    SHIPWRECKED(id = 353, slot = 271, varpId = 9, bitId = 20, songName = "Shipwrecked", regionOptions = arrayOf(14391)),
    SHOWDOWN(id = 311, slot = 249, varpId = 8, bitId = 21, songName = "Showdown", regionOptions = arrayOf(-1)),
    SIGMUNDS_SHOWDOWN(id = 640, slot = 420, varpId = 14, bitId = 15, songName = "Sigmund's Showdown", regionOptions = arrayOf(-1)),
    THE_SLAYER(id = 341, slot = 267, varpId = 9, bitId = 13, songName = "The Slayer", regionOptions = arrayOf(-1)),
    SLICE_OF_SILENT_MOVIE(id = 281, slot = 464, varpId = 15, bitId = 29, songName = "Slice of Silent Movie", regionOptions = arrayOf(-1)),
    SLICE_OF_STATION(id = 275, slot = 466, varpId = 15, bitId = 24, songName = "Slice of Station", regionOptions = arrayOf(-1)),
    SLITHER_AND_THITHER(id = 510, slot = 372, varpId = 12, bitId = 7, songName = "Slither and Thither", regionOptions = arrayOf(-1)),
    SLUG_A_BUG_BALL(id = 201, slot = 431, varpId = 14, bitId = 29, songName = "Slug a Bug Ball", regionOptions = arrayOf(-1)),
    SNOWFLAKE_AND_MY_ARM(id = 589, slot = 580, varpId = 18, bitId = 26, songName = "Snowflake & My Arm", regionOptions = arrayOf(-1)),
    SOJOURN(id = 257, slot = 213, varpId = 7, bitId = 17, songName = "Sojourn", regionOptions = arrayOf(-1)),
    SONG_OF_THE_ELVES(id = 645, slot = 616, varpId = 19, bitId = 29, songName = "Song of the Elves", regionOptions = arrayOf(-1)),
    SOUL_FALL(id = 444, slot = 515, varpId = 5, bitId = 28, songName = "Soul Fall", regionOptions = arrayOf(-1)),
    SOUNDSCAPE(id = 80, slot = 122, varpId = 4, bitId = 15, songName = "Soundscape", regionOptions = arrayOf(-1)),
    SPHINX(id = 387, slot = 296, varpId = 10, bitId = 14, songName = "Sphinx", regionOptions = arrayOf(13100)),
    SPIRIT(id = 175, slot = 18 , varpId = 4, bitId = 16, songName = "Spirit", regionOptions = arrayOf(12597)),
    SPIRITS_OF_THE_ELID(id = 462, slot = 347, varpId = 11, bitId = 11, songName = "Spirits of the Elid", regionOptions = arrayOf(-1)),
    SPLENDOUR(id = 77, slot = 55 , varpId = 4, bitId = 17, songName = "Splendour", regionOptions = arrayOf(11574)),
    SPOOKY(id = 333, slot = 36 , varpId = 4, bitId = 18, songName = "Spooky", regionOptions = arrayOf(12340)),
    SPOOKY_2(id = 11, slot = 229, varpId = 7, bitId = 26, songName = "Spooky 2", regionOptions = arrayOf(-1)),
    SPOOKY_JUNGLE(id = 129, slot = 78 , varpId = 4, bitId = 19, songName = "Spooky Jungle", regionOptions = arrayOf(-1)),
    THE_SPURNED_DEMON(id = 662, slot = 613, varpId = 19, bitId = 27, songName = "The Spurned Demon", regionOptions = arrayOf(-1)),
    STAGNANT(id = 241, slot = 197, varpId = 7, bitId = 1, songName = "Stagnant", regionOptions = arrayOf(13876)),
    STAND_UP_AND_BE_COUNTED(id = 656, slot = 619, varpId = 20, bitId = 0, songName = "Stand Up and Be Counted", regionOptions = arrayOf(-1)),
    STARLIGHT(id = 108, slot = 144, varpId = 4, bitId = 20, songName = "Starlight", regionOptions = arrayOf(11925,12181)),
    START(id = 151, slot = 37 , varpId = 4, bitId = 21, songName = "Start", regionOptions = arrayOf(12339)),
    STILL_NIGHT(id = 111, slot = 30 , varpId = 4, bitId = 22, songName = "Still Night", regionOptions = arrayOf(13108)),
    STILLNESS(id = 319, slot = 261, varpId = 8, bitId = 26, songName = "Stillness", regionOptions = arrayOf(-1)),
    STORM_BREW(id = 568, slot = 384, varpId = 13, bitId = 8, songName = "Storm Brew", regionOptions = arrayOf(-1)),
    STRANDED(id = 292, slot = 260, varpId = 8, bitId = 10, songName = "Stranded", regionOptions = arrayOf(-1)),
    STRANGE_PLACE(id = 470, slot = 331, varpId = 11, bitId = 17, songName = "Strange Place", regionOptions = arrayOf(-1)),
    STRATOSPHERE(id = 243, slot = 199, varpId = 7, bitId = 3, songName = "Stratosphere", regionOptions = arrayOf(-1)),
    STRENGTH_OF_SARADOMIN(id = 391, slot = 485, varpId = 16, bitId = 11, songName = "Strength of Saradomin", regionOptions = arrayOf(-1)),
    STUCK_IN_THE_MIRE(id = 607, slot = 590, varpId = 19, bitId = 4, songName = "Stuck in the Mire", regionOptions = arrayOf(-1)),
    SUBTERRANEA(id = 517, slot = 337, varpId = 12, bitId = 10, songName = "Subterranea", regionOptions = arrayOf(-1)),
    SUNBURN(id = 267, slot = 219, varpId = 7, bitId = 23, songName = "Sunburn", regionOptions = arrayOf(13357,12846)),
    SUPERSTITION(id = 265, slot = 156, varpId = 9, bitId = 5, songName = "Superstition", regionOptions = arrayOf(-1)),
    SUSPICIOUS(id = 308, slot = 248, varpId = 8, bitId = 20, songName = "Suspicious", regionOptions = arrayOf(-1)),
    TALE_OF_KELDAGRIM(id = 395, slot = 280, varpId = 10, bitId = 21, songName = "Tale of Keldagrim", regionOptions = arrayOf(-1)),
    TALKING_FOREST(id = 140, slot = 72 , varpId = 4, bitId = 23, songName = "Talking Forest", regionOptions = arrayOf(-1)),
    A_TASTE_OF_HOPE(id = 555, slot = 563, varpId = 18, bitId = 9, songName = "A Taste of Hope", regionOptions = arrayOf(-1)),
    TEARS_OF_GUTHIX(id = 397, slot = 299, varpId = 10, bitId = 23, songName = "Tears of Guthix", regionOptions = arrayOf(-1)),
    TECHNOLOGY(id = 296, slot = 242, varpId = 8, bitId = 14, songName = "Technology", regionOptions = arrayOf(-1)),
    TEMPEST(id = 518, slot = 541, varpId = 17, bitId = 20, songName = "Tempest", regionOptions = arrayOf(-1)),
    TEMPLE(id = 307, slot = 247, varpId = 8, bitId = 19, songName = "Temple", regionOptions = arrayOf(-1)),
    TEMPLE_OF_LIGHT(id = 376, slot = 332, varpId = 10, bitId = 6, songName = "Temple of Light", regionOptions = arrayOf(-1)),
    THE_TERRIBLE_TOWER(id = 339, slot = 265, varpId = 9, bitId = 11, songName = "The Terrible Tower", regionOptions = arrayOf(13623,13624)),
    THAT_SULLEN_HALL(id = 440, slot = 504, varpId = 16, bitId = 27, songName = "That Sullen Hall", regionOptions = arrayOf(-1)),
    THEME(id = 109, slot = 92 , varpId = 4, bitId = 27, songName = "Theme", regionOptions = arrayOf(-1)),
    A_THORN_IN_MY_SIDE(id = 601, slot = 595, varpId = 19, bitId = 9, songName = "A Thorn in my Side", regionOptions = arrayOf(-1)),
    THRALL_OF_THE_SERPENT(id = 433, slot = 500, varpId = 13, bitId = 12, songName = "Thrall of the Serpend", regionOptions = arrayOf(-1)),
    THRONE_OF_THE_DEMON(id = 379, slot = 286, varpId = 10, bitId = 9, songName = "Throne of the Demon", regionOptions = arrayOf(-1)),
    TIME_OUT(id = 242, slot = 200, varpId = 7, bitId = 4, songName = "Time Out", regionOptions = arrayOf(11590,11591,11846,11847)), // Maze Random Event
    TIME_TO_MINE(id = 369, slot = 281, varpId = 10, bitId = 1, songName = "Time To Mine", regionOptions = arrayOf(-1)),
    TIPTOE(id = 338, slot = 358, varpId = 9, bitId = 10, songName = "Tiptoe", regionOptions = arrayOf(12440)),
    TITLE_FIGHT(id = 525, slot = 350, varpId = 12, bitId = 15, songName = "Title Fight", regionOptions = arrayOf(-1)),
    TOMB_RAIDER(id = 591, slot = 397, varpId = 13, bitId = 18, songName = "Tomb Raider", regionOptions = arrayOf(-1)),
    TOMORROW(id = 105, slot = 418, varpId = 6, bitId = 3, songName = "Tomorrow", regionOptions = arrayOf(12081)),
    TOO_MAY_COOKS(id = 386, slot = 393, varpId = 13, bitId = 14, songName = "Too Many Cooks...", regionOptions = arrayOf(-1)),
    THE_TOWER_OF_VOICES(id = 648, slot = 605, varpId = 19, bitId = 19, songName = "The Tower of Voices", regionOptions = arrayOf(-1)),
    THE_TOWER(id = 133, slot = 91 , varpId = 4, bitId = 26, songName = "The Tower", regionOptions = arrayOf(-1)),
    THE_TRADE_PARADE(id = 496, slot = 501, varpId = 11, bitId = 30, songName = "The Trade Parade", regionOptions = arrayOf(-1)), // Grand Exchange
    TRAHAEARN_TOIL(id = 649, slot = 611, varpId = 19, bitId = 25, songName = "Trahaearn Toil", regionOptions = arrayOf(-1)),
    TRAWLER(id = 38, slot = 150, varpId = 4, bitId = 28, songName = "Trawler", regionOptions = arrayOf(-1)),
    TRAWLER_MINOR(id = 51, slot = 151, varpId = 4, bitId = 29, songName = "Trawler Minor", regionOptions = arrayOf(-1)),
    TREE_SPIRITS(id = 130, slot = 118, varpId = 4, bitId = 30, songName = "Tree Spirits", regionOptions = arrayOf(-1)),
    TREMBLE(id = 187, slot = 194, varpId = 6, bitId = 29, songName = "Tremble", regionOptions = arrayOf(-1)),
    TRIBAL(id = 165, slot = 84 , varpId = 5, bitId = 0, songName = "Tribal", regionOptions = arrayOf(-1)),
    TRIBAL_2(id = 94, slot = 86 , varpId = 5, bitId = 1, songName = "Tribal 2", regionOptions = arrayOf(-1)),
    TRIBAL_BACKGROUND(id = 162, slot = 81 , varpId = 4, bitId = 31, songName = "Tribal Background", regionOptions = arrayOf(-1)),
    TRINITY(id = 192, slot = 64 , varpId = 5, bitId = 2, songName = "Trinity", regionOptions = arrayOf(-1)),
    TROLL_SHUFFLE(id = 592, slot = 579, varpId = 18, bitId = 25, songName = "Troll Shuffle", regionOptions = arrayOf(-1)),
    TROUBLE_BREWING(id = 611, slot = 401, varpId = 13, bitId = 26, songName = "Trouble Brewing", regionOptions = arrayOf(-1)),
    TROUBLED(id = 183, slot = 130, varpId = 5, bitId = 3, songName = "Troubled", regionOptions = arrayOf(11833)),
    TROUBLED_WATERS(id = 421, slot = 489, varpId = 16, bitId = 15, songName = "Troubled Waters", regionOptions = arrayOf(-1)),
    TWILIGHT(id = 88, slot = 185, varpId = 6, bitId = 19, songName = "Twilight", regionOptions = arrayOf(-1)),
    TZHAAR(id = 473, slot = 330, varpId = 11, bitId = 19, songName = "TzHaar!", regionOptions = arrayOf(-1)),
    UNDEAD_DUNGEON(id = 214, slot = 461, varpId = 15, bitId = 23, songName = "Undead Dungeon", regionOptions = arrayOf(-1)),
    UNDERCURRENT(id = 176, slot = 111, varpId = 6, bitId = 10, songName = "Undercurrent", regionOptions = arrayOf(12345)),
    UNDERGROUND(id = 179, slot = 120, varpId = 5, bitId = 4, songName = "Underground", regionOptions = arrayOf(13368,11416)),
    UNDERGROUND_PASS(id = 323, slot = 152, varpId = 5, bitId = 6, songName = "Underground Pass", regionOptions = arrayOf(-1)),
    UNDERSTANDING(id = 131, slot = 192, varpId = 6, bitId = 27, songName = "Understanding", regionOptions = arrayOf(-1)),
    UNKNOWN_LAND(id = 3, slot = 38 , varpId = 5, bitId = 5, songName = "Unknown Land", regionOptions = arrayOf(12338)),
    UNTOUCHABLE(id = 300, slot = 476, varpId = 16, bitId = 6, songName = "Untouchable", regionOptions = arrayOf(-1)),
    UPCOMING(id = 70, slot = 73 , varpId = 5, bitId = 7, songName = "Upcoming", regionOptions = arrayOf(-1)),
    UPPER_DEPTHS(id = 492, slot = 531, varpId = 17, bitId = 10, songName = "Upper Depths", regionOptions = arrayOf(-1)),
    VANESCULA(id = 562, slot = 560, varpId = 18, bitId = 6, songName = "Vanescula", regionOptions = arrayOf(-1)),
    VENTURE(id = 75, slot = 10 , varpId = 5, bitId = 8, songName = "Venture", regionOptions = arrayOf(13364)),
    VENTURE_2(id = 45, slot = 11 , varpId = 6, bitId = 8, songName = "Venture 2", regionOptions = arrayOf(-1)),
    VICTORY_IS_MINE(id = 528, slot = 351, varpId = 12, bitId = 16, songName = "Victory is Mine", regionOptions = arrayOf(-1)),
    VILLAGE(id = 61, slot = 188, varpId = 6, bitId = 22, songName = "Village", regionOptions = arrayOf(13878)),
    VISION(id = 85, slot = 39 , varpId = 5, bitId = 9, songName = "Vision", regionOptions = arrayOf(12337)),
    VOLCANIC_VIKINGS(id = 225, slot = 438, varpId = 14, bitId = 24, songName = "Volcanic Vikings", regionOptions = arrayOf(-1)),
    VOODOO_CULT(id = 31, slot = 155, varpId = 5, bitId = 10, songName = "Voodoo Cult", regionOptions = arrayOf(-1)),
    VOYAGE(id = 32, slot = 90 , varpId = 5, bitId = 11, songName = "Voyage", regionOptions = arrayOf(-1)),
    WAKING_DREAM(id = 622, slot = 410, varpId = 14, bitId = 2, songName = "Walking Dream", regionOptions = arrayOf(-1)),
    A_WALK_IN_THE_WOODS(id = 636, slot = 587, varpId = 19, bitId = 1, songName = "A Walk in the Woods", regionOptions = arrayOf(-1)),
    THE_WALKING_DEAD(id = 551, slot = 550, varpId = 17, bitId = 29, songName = "The Walking Dead", regionOptions = arrayOf(-1)),
    WANDER(id = 49, slot = 49 , varpId = 5, bitId = 12, songName = "Wander", regionOptions = arrayOf(12083)),
    WARPATH(id = 427, slot = 495, varpId = 16, bitId = 23, songName = "Warpath", regionOptions = arrayOf(-1)), // Unlocked in Clan Wars Arena -- Random Between this song and Clan Wars Song -- re-enter to unlock both
    WARRIOR(id = 295, slot = 240, varpId = 8, bitId = 13, songName = "Warrior", regionOptions = arrayOf(-1)),
    WARRIORS_GUILD(id = 634, slot = 416, varpId = 14, bitId = 7, songName = "Warriors' Guild", regionOptions = arrayOf(-1)),
    WATERFALL(id = 82, slot = 89 , varpId = 5, bitId = 13, songName = "Waterfall", regionOptions = arrayOf(-1)),
    WATERLOGGED(id = 244, slot = 203, varpId = 7, bitId = 7, songName = "Waterlogged", regionOptions = arrayOf(13877,14133)),
    WAY_OF_THE_ENCHANTER(id = 626, slot = 414, varpId = 14, bitId = 6, songName = "Way of the Enchanter", regionOptions = arrayOf(-1)),
    WAY_OF_THE_WYRM(id = 595, slot = 583, varpId = 18, bitId = 29, songName = "Way of the Wyrm", regionOptions = arrayOf(-1)),
    WAYWARD(id = 394, slot = 304, varpId = 10, bitId = 20, songName = "Wayward", regionOptions = arrayOf(-1)),
    WE_ARE_THE_FAIRIES(id = 126, slot = 421, varpId = 14, bitId = 18, songName = "We Are the Fairies", regionOptions = arrayOf(-1)),
    WELCOME_TO_MY_NIGHTMARE(id = 578, slot = 566, varpId = 18, bitId = 12, songName = "Welcoe to my Nightmare", regionOptions = arrayOf(-1)),
    WELCOME_TO_THE_THEATRE(id = 556, slot = 562, varpId = 18, bitId = 8, songName = "Welcome to the Theatre", regionOptions = arrayOf(-1)),
    WELL_OF_VOYAGE(id = 271, slot = 226, varpId = 7, bitId = 31, songName = "Well of Voyage", regionOptions = arrayOf(-1)),
    WHERE_EAGLES_LAIR(id = 620, slot = 361, varpId = 15, bitId = 0, songName = "Where Eagles Lair", regionOptions = arrayOf(-1)),
    WILD_SIDE(id = 475, slot = 322, varpId = 11, bitId = 20, songName = "Wild Side", regionOptions = arrayOf(12092,12348)),
    WILDERNESS(id = 435, slot = 128, varpId = 5, bitId = 14, songName = "Wilderness", regionOptions = arrayOf(12346,11832)),
    WILDERNESS_2(id = 42, slot = 132, varpId = 5, bitId = 15, songName = "Wilderness 2", regionOptions = arrayOf(12091,12347)),
    WILDERNESS_3(id = 43, slot = 62 , varpId = 5, bitId = 16, songName = "Wilderness 3", regionOptions = arrayOf(11834)),
    WILDWOOD(id = 8, slot = 109, varpId = 9, bitId = 0, songName = "Wildwood", regionOptions = arrayOf(12344)),
    WINTER_FUNFAIR(id = 526, slot = 545, varpId = 17, bitId = 24, songName = "Winter Funfair", regionOptions = arrayOf(-1)), // Unlocked during 2017 Christmas Event
    WITCHING(id = 14, slot = 23 , varpId = 5, bitId = 17, songName = "Witching", regionOptions = arrayOf(13114,13370)),
    WOE_OF_THE_WYVERN(id = 529, slot = 143, varpId = 12, bitId = 17, songName = "Woe of the Wyvern", regionOptions = arrayOf(-1)),
    WOLF_MOUNTAIN(id = 189, slot = 110, varpId = 6, bitId = 6, songName = "Wolf Mountain", regionOptions = arrayOf(12603,12859)),
    WONDER(id = 34, slot = 129, varpId = 5, bitId = 18, songName = "Wonder", regionOptions = arrayOf(11831)),
    WONDEROUS(id = 81, slot = 63 , varpId = 5, bitId = 19, songName = "Wonderous", regionOptions = arrayOf(-1)),
    WOODLAND(id = 255, slot = 210, varpId = 7, bitId = 14, songName = "Woodland", regionOptions = arrayOf(-1)),
    WORK_WORK_WORK(id = 237, slot = 442, varpId = 15, bitId = 2, songName = "Work, Work, Work", regionOptions = arrayOf(-1)),
    WORKSHOP(id = 15, slot = 163, varpId = 5, bitId = 20, songName = "Workshop", regionOptions = arrayOf(12084)),
    WRATH_AND_RUIN(id = 565, slot = 385, varpId = 13, bitId = 7, songName = "Wrath and Ruin", regionOptions = arrayOf(-1)),
    XENOPHOBE(id = 524, slot = 339, varpId = 12, bitId = 14, songName = "Xenophobe", regionOptions = arrayOf(-1)),
    YESTERYEAR(id = 145, slot = 177, varpId = 6, bitId = 1, songName = "Yesteryear", regionOptions = arrayOf(12849)),
    ZAMORAK_ZOO(id = 399, slot = 486, varpId = 16, bitId = 10, songName = "Zamorak Zoo", regionOptions = arrayOf(-1)),
    ZEALOT(id = 146, slot = 170, varpId = 6, bitId = 12, songName = "Zealot", regionOptions = arrayOf(10827)),
    ZOGRE_DANCE(id = 392, slot = 303, varpId = 10, bitId = 18, songName = "Zogre Dance", regionOptions = arrayOf(-1)),
    ZOMBIISM(id = 238, slot = 459, varpId = 15, bitId = 19, songName = "Zombiism", regionOptions = arrayOf(-1));

    companion object {
        /**
         * The cached array of enum definitions
         */
        val values = enumValues<MusicTracks>()

        val musicDefinitions = MusicTracks.values.associate { it.id to it }
    }
}